### ISSUE TITLE
Training?

### ISSUE THREAD

**Issue by apappu97** [kigawas/coheoka#2]
Hi, I had a quick question about training. I believe the Barzilay paper that is referenced trains the entity transitions on a large corpus of text, in order to learn what kind of entity transitions are probable in coherent text. I don't see train code in this repo in order to learn the probable transitions for the entity grid model -- is there a way to train the entity grid model? Thanks!

**Comment by kigawas** [comment]
Thanks for asking.

About this part, I offloaded it to Stanford CoreNLP

**Comment by caroarriaga** [comment]
Hi, I am a bit confused by this answer. Could you please expand on it? (I'm new in the NLP field)

On another note, I saw you have the Corpus directory with the test.txt file to evaluate coherence. It seems the assessments.py file is calling for some pickle files that are not in the repo. Could you please clarify how to produce those pickle files and/or if they are available somewhere?

Thank you!

**Comment by kigawas** [comment]
@caroarriaga It's just `fit` in scikit-learn: https://github.com/kigawas/coheoka/blob/master/coheoka/evaluator.py#L128
